//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdsClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdsClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given string is incorrectly formatted to be a valid AmsAddress..
        /// </summary>
        internal static string AmsAddressParseInvalidFormat {
            get {
                return ResourceManager.GetString("AmsAddressParseInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given command ID is invalid. Check http://infosys.beckhoff.com/content/1033/tcadsamsspec/html/tcadsamsspec_amsheader.htm?id=18623#Command%20Id for allowed values..
        /// </summary>
        internal static string AmsHeaderInvalidCommandId {
            get {
                return ResourceManager.GetString("AmsHeaderInvalidCommandId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given state flags are invalid. Check http://infosys.beckhoff.com/content/1033/tcadsamsspec/html/tcadsamsspec_amsheader.htm?id=18623#State%20Flags for allowed values..
        /// </summary>
        internal static string AmsHeaderInvalidStateFlags {
            get {
                return ResourceManager.GetString("AmsHeaderInvalidStateFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given string is incorrectly formatted to be a valid AMSNetId..
        /// </summary>
        internal static string AmsNetIdParseInvalidFormat {
            get {
                return ResourceManager.GetString("AmsNetIdParseInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each part of an AMSNetId has a maximum value of 256..
        /// </summary>
        internal static string AmsNetIdParseOverflow {
            get {
                return ResourceManager.GetString("AmsNetIdParseOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exactly 6 bytes are required to form a valid AMSNetId..
        /// </summary>
        internal static string AmsNetIdValueOutOfRange {
            get {
                return ResourceManager.GetString("AmsNetIdValueOutOfRange", resourceCulture);
            }
        }
    }
}
